package org.team4u.test;

import com.alibaba.druid.pool.DruidDataSource;
import org.team4u.dao.core.Dao;
import org.team4u.dao.core.SimpleDao;
import org.team4u.sql.builder.Sql;

import javax.sql.DataSource;

/**
 * @author Jay Wu
 */
public class TestUtil {

    public static DataSource createDataSource() {
        DruidDataSource ds = new DruidDataSource();
        ds.setUrl("jdbc:hsqldb:mem:db");
        ds.setUsername("sa");
        ds.setPassword("");
        ds.setInitialSize(1);
        return ds;
    }

    public static SimpleDao createDao() {
        return new SimpleDao(createDataSource());
    }

    public static SimpleDao createAndInitDao() {
        SimpleDao dao = createDao();
        initTables(dao);
        return dao;
    }

    public static void initTables(Dao dao) {
        dao.execute(new Sql().setContent("CREATE TABLE system_config\n" +
                "(\n" +
                "    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1),\n" +
                "    is_enabled SMALLINT DEFAULT 1 NOT NULL,\n" +
                "    type VARCHAR(32) DEFAULT '' NOT NULL,\n" +
                "    name VARCHAR(255) DEFAULT '' NOT NULL,\n" +
                "    value VARCHAR(4000) DEFAULT '' NOT NULL,\n" +
                "    sequence_no BIGINT DEFAULT 0 NOT NULL,\n" +
                "    description VARCHAR(255) DEFAULT '' NOT NULL,\n" +
                "    create_time TIMESTAMP DEFAULT '2018-01-01 00:00:00' NOT NULL,\n" +
                "    update_time TIMESTAMP DEFAULT '2018-01-01 00:00:00' NOT NULL,\n" +
                "    PRIMARY KEY (id)\n" +
                ");"));
    }
}